title: Acht
author: Dean Cook
description: > # description of the site (multiple lines allowed)
  Navigating the evergrowing complexity in our modern world.

email: deanrobertcook@gmail.com # email of site's author
url: https://deanrobertcook.github.io # root address of the site

permalink: /:slug.html

#https://github.com/riggraz/no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed
